# src/config/config.yml

defaults:
  notifications:
    error_channel: "-1002922469529"   # soporte técnico
  message_policy:
    preserve_hours: 24                # futura retención de mensajes

betburger_profiles:
  bet365_valuebets:
    channel_id: "-1002993087103"
    ui_filter_name: "Bet365 vs Pinnacle"
    description: "Betburger Profile 1 - High ROI alerts"
    platform: betburger
    type: valuebets
    filters:
      - min_roi: 5.0
      - sports: ["football", "tennis"]
      - bookmakers: ["bet365"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "selection_b.bookmaker", "selection_b.odd", "roi_pct"]

  winamax-valuebets:
    channel_id: "-1002868073429"
    ui_filter_name: "Winamax/Tonybet vs Pinnacle"
    description: "Betburger Profile 2 - Basketball alerts"
    platform: betburger
    type: valuebets
    filters:
      - min_roi: 3.0
      - sports: ["basketball"]
      - bookmakers: ["winamax"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "selection_b.bookmaker", "selection_b.odd", "roi_pct"]

  codere_valuebets:
    channel_id: "-1003085949789"
    ui_filter_name: "Codere vs Pinnacle"
    description: "Betburger Profile 3 - All sports low ROI"
    platform: betburger
    type: valuebets
    filters:
      - min_roi: 2.0
      - bookmakers: ["codere"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "selection_b.bookmaker", "selection_b.odd", "roi_pct"]

  retabet_valuebets:
    channel_id: "-1002972972758"
    ui_filter_name: "Betfair/Pokerstars vs Pinnacle"
    description: "Betburger Profile 4 - High stakes"
    platform: betburger
    type: valuebets
    filters:
      - min_roi: 4.0
      - bookmakers: ["retabet"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "selection_b.bookmaker", "selection_b.odd", "roi_pct"]

  winamax-bet365:
    channel_id: "-1003088121672"
    ui_filter_name: "Wina/Tony vs Bet365"
    description: "Betburger Profile 5 - Quick bets"
    platform: betburger
    type: valuebets
    filters:
      - min_roi: 3.5
      - bookmakers: ["winamax", "bet365"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "selection_b.bookmaker", "selection_b.odd", "roi_pct"]

  filtro_6:
    channel_id: "-1003073937037"
    ui_filter_name: "Filtro 6"
    description: "Betburger Tabs - Filtro 6"
    platform: betburger
    type: valuebets
    filters:
      - min_roi: 3.0
      - bookmakers: ["bet365"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "selection_b.bookmaker", "selection_b.odd", "roi_pct"]

surebet_profiles:
  ev-surebets:
    channel_id: "-1003051607294"
    ui_filter_name: "Filtro 3"
    description: "Surebet Valuebets - Main channel"
    platform: surebet
    type: valuebets
    filters:
      - min_value: 5.0
      - bookmakers: ["pinnacle", "bet365"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "value_pct"]
    defaults:
      selection_a:
        bookmaker: "Winamax"
      selection_b:
        bookmaker: "Bet365"
      market_label: ""

  filtro_1:
    channel_id: "-1002915431056"
    ui_filter_name: "Filtro 1"
    description: "Surebet Valuebets - Main channel"
    platform: surebet
    type: valuebets
    filters:
      - min_value: 5.0
      - bookmakers: ["pinnacle", "bet365"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "value_pct"]
    defaults:
      selection_a:
        bookmaker: "Winamax"
      selection_b:
        bookmaker: "Bet365"
      market_label: ""

  filtro_2:
    channel_id: "-1003072894250"
    ui_filter_name: "Filtro 2"
    description: "Surebet Valuebets - Main channel"
    platform: surebet
    type: valuebets
    filters:
      - min_value: 5.0
      - bookmakers: ["pinnacle", "bet365"]
    required_fields: ["timestamp_utc", "match", "selection_a.bookmaker", "selection_a.odd", "value_pct"]
    defaults:
      selection_a:
        bookmaker: "Winamax"
      selection_b:
        bookmaker: "Bet365"
      market_label: ""

support:
  technical_alerts:
    channel_id: "-1002922469529"
    description: "Technical errors and reconnection alerts"

# Si quisieras mapear filtros UI por pestaña desde config (no necesario si lo haces manual en el navegador):
# betburger_tab_filters: []