# Mapping of filters to Telegram channels
# Each profile/filter gets its own channel

betburger_profiles:
  profile_1:
    channel_id: "@channel_profile_1"
    description: "Betburger Profile 1 - High ROI alerts"
    filters:
      - min_roi: 5.0
      - sports: ["football", "tennis"]
  
  profile_2:
    channel_id: "@channel_profile_2" 
    description: "Betburger Profile 2 - Basketball alerts"
    filters:
      - min_roi: 3.0
      - sports: ["basketball"]
  
  profile_3:
    channel_id: "@channel_profile_3"
    description: "Betburger Profile 3 - All sports low ROI"
    filters:
      - min_roi: 2.0

  profile_4:
    channel_id: "@channel_profile_4"
    description: "Betburger Profile 4 - High stakes"
    filters:
      - min_roi: 4.0

  profile_5:
    channel_id: "@channel_profile_5"
    description: "Betburger Profile 5 - Quick bets"
    filters:
      - min_roi: 3.5

  profile_6:
    channel_id: "@channel_profile_6"
    description: "Betburger Profile 6 - Premium alerts"
    filters:
      - min_roi: 6.0

surebet_profiles:
  valuebets_main:
    channel_id: "@surebet_valuebets"
    description: "Surebet Valuebets - Main channel"
    filters:
      - min_value: 5.0
      - bookmakers: ["pinnacle", "bet365"]

# Support channels
support:
  technical_alerts:
    channel_id: "@bot_technical_support"
    description: "Technical errors and reconnection alerts"
